<?php $host = '//' . $_SERVER["HTTP_HOST"] ?>
<footer class="l-footer">
    <ul class="wrap cf">
        <li class="logo">
            <div><img src="<?php echo $host; ?>/assets/img/common/makuou.png" alt="幕王"></div>
            <div class="btn red"><a href="">オリジナル横断幕を作る</a></div>
            <div class="btn org"><a href="">仕様以外の注文について</a></div>
            <div class="btn org"><a href="">サンプルのご請求はこちら</a></div>
        </li>
        <li>
            <dl>
                <dt>初めての方へ</dt>
                <dd><a href="#">幕王について</a></dd>
                <dd><a href="#">会員制システムについて</a></dd>
            </dl>
            <dl>
                <dt>ご利用案内</dt>
                <dd><a href="#">価格表</a></dd>
                <dd><a href="#">ご注文の流れ</a></dd>
                <dd><a href="#">納期・お届けについて</a></dd>
                <dd><a href="#">お支払い方法</a></dd>
                <dd><a href="#">発送方法・送料</a></dd>
                <dd><a href="#">よくあるご質問</a></dd>
            </dl>
        </li>
        <li>
            <dl>
                <dt>ご注文について</dt>
                <dd><a href="#">デザインレイアウト調整手順</a></dd>
                <dd><a href="#">追加注文について</a></dd>
                <dd><a href="#">キャンセル・交換・返品について</a></dd>
                <dd><a href="#">データ入稿について</a></dd>
            </dl>
            <dl>
                <dt>おすすめTips</dt>
                <dd><a href="#">素材について</a></dd>
                <dd><a href="#">サイズについて</a></dd>
                <dd><a href="#">お客様の事例紹介</a></dd>
                <dd><a href="#">サンプル請求</a></dd>
            </dl>
        </li>
        <li>
            <dl>
                <dt>運営会社概要</dt>
                <dd><a href="#">運営会社概要</a></dd>
                <dd><a href="#">ご利用規約</a></dd>
                <dd><a href="#">お客様の事例紹介</a></dd>
                <dd><a href="#">プライバシーポリシー</a></dd>
                <dd><a href="#">特定取引法に基づく表示</a></dd>
                <dd><a href="#">お問い合わせ</a></dd>
                <dd><a href="#">サイトマップ</a></dd>
            </dl>
            <div><a href="#" target="_blank"><img src="<?php echo $host; ?>/assets/img/common/bnr_inkjethouse.png" alt="インクジェットハウス"></a></div>
            <div><a href="#" target="_blank"><img src="<?php echo $host; ?>/assets/img/common/bnr_signhouse.png" alt="サインハウス"></a></div>
        </li>
    </ul>
    <address>copyright &copy; Osakabisou All rights reserved.</address>
</footer>