<?php $host = '//' . $_SERVER["HTTP_HOST"] ?>
<footer class="l-footer">
    <ul class="wrap cf">
        <li class="logo">
            <div><img src="<?php echo $host; ?>/assets/img/common/makuou.png" alt="幕王"></div>
			<div class="btn red"><a href="<?php echo $host; ?>/search/">オリジナル横断幕を作る</a></div>
			<div class="btn org"><a href="<?php echo $host; ?>/sample/">サンプルのご請求はこちら</a></div>
			<div class="btn org"><a href="<?php echo $host; ?>/login/index.php">会員ログイン</a></div>
        </li>
        <li>
            <dl>
                <dt>初めての方へ</dt>
				<dd><a href="<?php echo $host; ?>">幕王について</a></dd>
				<dd><a href="<?php echo $host; ?>/regist/">会員登録</a></dd>
				<dd><a href="<?php echo $host; ?>/example/">ギャラリー（事例紹介）</a></dd>
            </dl>
            <dl>
                <dt>ご利用ガイド</dt>
				<dd><a href="<?php echo $host; ?>/guide/#ank-01">ご注文の流れ</a></dd>
				<dd><a href="<?php echo $host; ?>/guide/#ank-02">納期・お届けについて</a></dd>
				<dd><a href="<?php echo $host; ?>/guide/#ank-03">お支払い方法</a></dd>
				<dd><a href="<?php echo $host; ?>/guide/#ank-04">発送方法・送料</a></dd>
            </dl>
        </li>
        <li>
            <dl>
                <dt>よくあるご質問</dt>
				<dd><a href="<?php echo $host; ?>/faq/">注文方法について</a></dd>
				<dd><a href="<?php echo $host; ?>/faq/">幕の仕様について</a></dd>
				<dd><a href="<?php echo $host; ?>/faq/">オリジナルのロゴや写真について</a></dd>
				<dd><a href="<?php echo $host; ?>/faq/">デザイン制作について</a></dd>
				<dd><a href="<?php echo $host; ?>/faq/">発送について</a></dd>
				<dd><a href="<?php echo $host; ?>/faq/">耐久性・アフターサポートについて</a></dd>
            </dl>
            <dl>
			<dt>ご案内</dt>
			<dd><a href="<?php echo $host; ?>/price/">価格表</a></dd>
			<dd><a href="<?php echo $host; ?>/material/">素材について</a></dd>
			<dd><a href="<?php echo $host; ?>/size/">サイズについて</a></dd>
			<dd><a href="<?php echo $host; ?>/option/">オプションについて</a></dd>
            </dl>
        </li>
        <li>
            <dl>
                <dt>運営会社概要</dt>
                <dd><a href="<?php echo $host; ?>/company/">運営会社概要</a></dd>
                <dd><a href="<?php echo $host; ?>/contract/">ご利用規約</a></dd>
				<dd><a href="<?php echo $host; ?>/privacy/">プライバシーポリシー</a></dd>
                <dd><a href="<?php echo $host; ?>/order/">特定取引法に基づく表示</a></dd>
                <dd><a href="<?php echo $host; ?>/contact/">お問い合わせ</a></dd>
            </dl>
        </li>
    </ul>
    <address>copyright &copy; Osakabisou All rights reserved.</address>
</footer>