<?php $host = '//' . $_SERVER["HTTP_HOST"] ?>

<header class="l-header">
    <div class="wrap cf">
        <div class="left">
            <div class="cf">
                <h1 class="logo"><a href="/"><img src="/assets/img/common/logo.png" alt="幕王"></a></h1>
                <ul class="head__nav">
                    <li><a href="#dummy">デザインを探す</a></li>
                    <li><a href="#dummy">サイズの選び方</a></li>
                    <li><a href="#dummy">実績を見る</a></li>
                    <li><a href="#dummy">会員登録</a></li>
                </ul>
            </div>
        </div>
        <div class="right sp_none">
            <div class="hour">
                <div><img src="/assets/img/common/header_tel.png" alt="0120-805-266"></div>
                <p class="time">営業時間　9:00～17:00　土日祝休み</p>
            </div>
        </div>
        <div class="right pc_none sp-ham">
            <a class="menu-trigger">
              <span></span>
              <span></span>
              <span></span>
            </a>
        </div>
    </div>
    <nav class="sp_none">
        <ul class="cf">
            <li><a href="/">HOME</a></li>
            <li><a href="#">横断幕を作る</a></li>
            <li><a href="#">ご注文の流れ</a></li>
            <li><a href="#">価格表</a></li>
            <li><a href="#">事例紹介</a></li>
            <li><a href="#">よくあるご質問</a></li>
            <li><a href="#">お問い合わせ</a></li>
        </ul>
    </nav>
</header>
<div class="sp-nav">
    <div class="hour">
        <div><a href="tel:0120805266"><img src="/assets/img/common/header_tel.png" alt="0120-805-266"></a></div>
                <p class="time">営業時間　9:00～17:00　土日祝休み</p>
    </div>
    <ul class="head__nav">
        <li><a href="#dummy">デザインを探す</a></li>
        <li><a href="#dummy">サイズの選び方</a></li>
        <li><a href="#dummy">実績を見る</a></li>
        <li><a href="#dummy">会員登録</a></li>
    </ul>
    <ul class="cf">
        <li><a href="/">HOME</a></li>
        <li><a href="#">横断幕を作る</a></li>
        <li><a href="#">テンプレートを検索</a></li>
        <li><a href="#">ご注文の流れ</a></li>
        <li><a href="#">価格表</a></li>
        <li><a href="#">事例紹介</a></li>
        <li><a href="#">よくあるご質問</a></li>
        <li><a href="#">お問い合わせ</a></li>
    </ul>
</div>

    
<aside>
    <div class="sidebtn"><img src="/assets/img/common/arrow_l_white.gif"></div>    
    <div class="sidenav">
        <div class="sidenav__link"><a href="#dummy">デザインを見る</a></div>
        <div class="sidenav__list">
            <dl>
                <dt><a href="#">ご利用ガイド</a></dt>
            </dl>
            <dl>
                <dt><a href="#">料金表を見る</a></dt>
            </dl>
            <dl>
                <dt><a href="#">スポーツから選ぶ</a></dt>
                <dd><a href="#">サッカー</a></dd>
                <dd><a href="#">野球</a></dd>
                <dd><a href="#">バスケ</a></dd>
                <dd><a href="#">他を見る</a></dd>
            </dl>
            <dl>
                <dt><a href="#">テイストから選ぶ</a></dt>
                <dd><a href="#">シンプル</a></dd>
                <dd><a href="#">熱血</a></dd>
                <dd><a href="#">スポーティ</a></dd>
                <dd><a href="#">他を見る</a></dd>
            </dl>
        </div>    
        <div class="sidenav__link2"><a href="#dummy">マイページを見る</a></div>
        <div class="sidenav__link2"><a href="#dummy">ログイン</a></div>
    </div>    
</aside>    
    
    