<?php $host = '//' . $_SERVER["HTTP_HOST"] ?>
<header class="l-header">
    <div class="wrap cf">
        <div class="left">
            <div class="cf">
                <h1 class="logo"><a href="/"><img src="<?php echo $host; ?>/assets/img/common/logo.png" alt="幕王"></a></h1>
                <div class="catch"><img src="<?php echo $host; ?>/assets/img/common/head_catch.png" alt="オリジナルの横断幕自分でデザイン気軽に発注"></div>
            </div>
        </div>
        <div class="right sp_none">
            <div class="login cf">
                <p class="name">ようこそゲスト様</p>
                <p class="btn"><a href="#">ログイン</a></p>
            </div>
            <div class="hour">
                <div><img src="<?php echo $host; ?>/assets/img/common/tel.png" alt="0120-805-266"></div>
                <div class="box_dot"><p>【営業時間】9:00～17:00　<span class="txt_blue">土</span><span class="txt_red">日祝</span>休み</p></div>
            </div>
        </div>
        <div class="right pc_none sp-ham">
            <a class="menu-trigger">
              <span></span>
              <span></span>
              <span></span>
            </a>
        </div>
    </div>
    <nav class="sp_none">
        <ul class="cf">
            <li><a href="/">HOME</a></li>
            <li><a href="#">横断幕を作る</a></li>
            <li><a href="#">テンプレートを検索</a></li>
            <li><a href="#">ご注文の流れ</a></li>
            <li><a href="#">価格表</a></li>
            <li><a href="#">事例紹介</a></li>
            <li><a href="#">よくあるご質問</a></li>
            <li><a href="#">お問い合わせ</a></li>
        </ul>
    </nav>
</header>
    <div class="sp-nav">
        <div class="login cf">
            <p class="name">ようこそゲスト様</p>
            <p class="btn"><a href="#">ログイン</a></p>
        </div>
        <div class="hour">
            <div><a href="tel:0120805266"><img src="<?php echo $host; ?>/assets/img/common/tel.png" alt="0120-805-266"></a></div>
            <div class="box_dot"><p>【営業時間】9:00～17:00　<span class="txt_blue">土</span><span class="txt_red">日祝</span>休み</p></div>
        </div>
        <ul class="cf">
            <li><a href="/">HOME</a></li>
            <li><a href="#">横断幕を作る</a></li>
            <li><a href="#">テンプレートを検索</a></li>
            <li><a href="#">ご注文の流れ</a></li>
            <li><a href="#">価格表</a></li>
            <li><a href="#">事例紹介</a></li>
            <li><a href="#">よくあるご質問</a></li>
            <li><a href="#">お問い合わせ</a></li>
        </ul>
    </div>