<div class="side">
<div class="side__tit"><img src="/assets/img/ordered/mypage_tit01.gif" alt="マイページメニュー"></div>
	<ul>
        <li><a href="/mypage/"><img src="/assets/img/ordered/mypage_menu07.png" alt="保存作品"></a></li>
        <li><a href="/save/"><img src="/assets/img/ordered/mypage_menu01.png" alt="保存作品"></a></li>
        <li><a href="/favorite/"><img src="/assets/img/ordered/mypage_menu02.png" alt="お気に入りテンプレート"></a></li>
		<li><a href="/member/"><img src="/assets/img/ordered/mypage_menu03.png" alt="登録情報編集"></a></li>
		<li><a href="/ordered/"><img src="/assets/img/ordered/mypage_menu04.png" alt="注文履歴"></a></li>
		<li><a href="/logout/"><img src="/assets/img/ordered/mypage_menu05.png" alt="ログアウト"></a></li>
		<li><a href="/cancell/"><img src="/assets/img/ordered/mypage_menu06.png" alt="退会"></a></li>
	</ul>
</div>